// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBClqiwe_MOVFisb_PCrvjSDbREFLEsLec',
    appId: '1:285311339049:web:b27ba0d9a1d74ee6c9aa38',
    messagingSenderId: '285311339049',
    projectId: 'restaurant-talks-flutter',
    authDomain: 'restaurant-talks-flutter.firebaseapp.com',
    storageBucket: 'restaurant-talks-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5f7fu1M1B13otM07t2U-R51xkRSZMMrU',
    appId: '1:285311339049:android:daa30dda45ed74aec9aa38',
    messagingSenderId: '285311339049',
    projectId: 'restaurant-talks-flutter',
    storageBucket: 'restaurant-talks-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLyObnKBFNQUOiSyIgWY4aaSCwpl0-EIY',
    appId: '1:285311339049:ios:7d9cbef4087fed23c9aa38',
    messagingSenderId: '285311339049',
    projectId: 'restaurant-talks-flutter',
    storageBucket: 'restaurant-talks-flutter.appspot.com',
    iosClientId:
        '285311339049-rj8hil4ss5fps6f0fdq3lh5mp1d41g5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantTalksFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLyObnKBFNQUOiSyIgWY4aaSCwpl0-EIY',
    appId: '1:285311339049:ios:7d9cbef4087fed23c9aa38',
    messagingSenderId: '285311339049',
    projectId: 'restaurant-talks-flutter',
    storageBucket: 'restaurant-talks-flutter.appspot.com',
    iosClientId:
        '285311339049-rj8hil4ss5fps6f0fdq3lh5mp1d41g5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantTalksFlutter',
  );
}
